spring:
  application:
    name: org-integrations-system
  profiles:
    active: default
  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8800

management:
    endpoints:
      web:
        exposure:
          include: refresh
